'use client'

import Link from 'next/link'
import { Footer, Header } from '@/components/site-chrome'
import { useLang } from '@/lib/i18n'

type Lang = 'bg' | 'de'

const copy = {
  de: {
    nav: ['Dienstleistungen', 'Vorteile', 'Kontakt'], login: 'Anmelden', toggle: 'BG',
    heroEyebrow: 'ENERGIE NEU GEDACHT', heroTitle: <>Mehr aus Ihrer<br /><em>Energie.</em></>, heroText: 'Wir helfen Ihnen, Energiekosten zu verstehen, zu optimieren und dauerhaft zu senken. Persönlich. Unabhängig. Transparent.', heroCta: 'Dienstleistungen ansehen', more: 'Mehr erfahren', energy: 'ENERGIE', simple: 'EINFACH', effective: 'WIRKSAM', trust: 'Vertrauen, das sich auszahlt', independent: 'unabhängig', available: 'für Sie da', potential: 'Potenzial', approach: 'UNSER ANSATZ', approachTitle: <>Energie verstehen.<br /><em>Vorteile nutzen.</em></>, approachText: 'Komplexe Energiethemen werden bei uns zu klaren Entscheidungen. Damit Sie sich auf das konzentrieren können, was wirklich zählt.', clearTitle: <>Klarheit statt<br />Kleingedrucktes.</>, clearText: 'Wir übersetzen Tarife und Zahlen in verständliche Empfehlungen – ohne Fachchinesisch.', independentTitle: <>Unabhängig<br />beraten.</>, independentText: 'Unsere Empfehlung richtet sich nach Ihren Zielen – nicht nach Provisionen.', serviceEyebrow: 'PREMIUM LEISTUNG', serviceTitle: <>Tarifanalyse mit <em>Smart-Meter.</em></>, serviceText: 'Wir analysieren Ihre Vertraege, optimieren Ihre Tarife und vermitteln ein Smart-Meter-Geraet, das Ihren Verbrauch in Echtzeit anzeigt.', serviceButton: 'Jetzt kaufen', footerLead: <>Ihre Energie. Ihre Entscheidung.<br />Wir machen sie einfacher.</>, navigation: 'Navigation', legal: 'Rechtliches', contact: 'Kontakt', weekdays: 'Mo–Fr, 9:00–18:00 Uhr', services: 'Dienstleistungen', privacy: 'Datenschutz', terms: 'AGB', imprint: 'Impressum'
  },
  bg: {
    nav: ['Услуги', 'Предимства', 'Контакт'], login: 'Вход', toggle: 'DE',
    heroEyebrow: 'ЕНЕРГИЯ, ПРЕОСМИСЛЕНА', heroTitle: <>Повече от Вашата<br /><em>енергия.</em></>, heroText: 'Помагаме Ви да разберете, оптимизирате и трайно намалите енергийните си разходи. Лично. Независимо. Прозрачно.', heroCta: 'Вижте всички услуги', more: 'Научете повече', energy: 'ЕНЕРГИЯ', simple: 'ЛЕСНО', effective: 'ЕФЕКТИВНО', trust: 'Доверие, което се изплаща', independent: 'независими', available: 'винаги до Вас', potential: 'потенциал', approach: 'НАШИЯТ ПОДХОД', approachTitle: <>Разберете енергията.<br /><em>Използвайте предимствата.</em></>, approachText: 'Сложните енергийни теми превръщаме в ясни решения, за да се фокусирате върху това, което наистина има значение.', clearTitle: <>Яснота вместо<br />дребен шрифт.</>, clearText: 'Превеждаме тарифите и числата в разбираеми препоръки – без сложен жаргон.', independentTitle: <>Независима<br />консултация.</>, independentText: 'Нашите препоръки са съобразени с Вашите цели – не с комисиони.', serviceEyebrow: 'ПРЕМИУМ УСЛУГА', serviceTitle: <>Тарифен анализ с <em>Smart-Meter.</em></>, serviceText: 'Анализираме договорите Ви, оптимизираме тарифите и осигуряваме Smart-Meter устройство за мониторинг в реално време.', serviceButton: 'Купи сега', footerLead: <>Вашата енергия. Вашето решение.<br />Ние го правим по-лесно.</>, navigation: 'Навигация', legal: 'Правна информация', contact: 'Контакт', weekdays: 'Пн–Пт, 9:00–18:00 ч.', services: 'Услуги', privacy: 'Поверителност', terms: 'Общи условия', imprint: 'Импресум'
  }
}

function Home() { const { lang } = useLang(); const t = copy[lang]; return <><Header /><main><section className="hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow">{t.heroEyebrow}</p><h1>{t.heroTitle}</h1><p className="hero-text">{t.heroText}</p><div className="hero-actions"><Link href="/dienstleistungen" className="hero-cta">{t.heroCta} <span>→</span></Link><Link href="#vorteile" className="text-link">{t.more} <span>↓</span></Link></div></div><div className="hero-art" aria-label="Energy efficiency"><div className="art-ring ring-one" /><div className="art-ring ring-two" /><div className="art-core"><span>24</span><small>{t.energy}</small></div><div className="art-label label-top">{t.simple}</div><div className="art-label label-bottom">{t.effective}</div></div></div></section><section className="trust"><div className="container trust-inner"><span>{t.trust}</span><div><b>100%</b><small>{t.independent}</small></div><div><b>24/7</b><small>{t.available}</small></div><div><b>∞</b><small>{t.potential}</small></div></div></section><section className="section" id="vorteile"><div className="container"><div className="section-intro"><p className="eyebrow">{t.approach}</p><h2>{t.approachTitle}</h2><p>{t.approachText}</p></div><div className="feature-grid"><div className="feature-card feature-main"><span className="card-number">01</span><div><h3>{t.clearTitle}</h3><p>{t.clearText}</p></div><span className="card-arrow">↗</span></div><div className="feature-card feature-light"><span className="card-number">02</span><div><h3>{t.independentTitle}</h3><p>{t.independentText}</p></div></div></div></div></section><section className="service-cta"><div className="container"><div className="service-cta-card"><div><p className="eyebrow">{t.serviceEyebrow}</p><h2>{t.serviceTitle}</h2><p>{t.serviceText}</p></div><div className="service-cta-aside"><span className="service-cta-price">198 €</span><Link href="/produkt/tarifanalyse-smart-meter" className="button button-dark">{t.serviceButton} <span>↗</span></Link></div></div></div></section></main><Footer /></> }

export function SitePage({ path = '/' }: { path?: string }) { return <Home /> }
export default function Page() { return <SitePage /> }

