'use client'

import { useState } from 'react'
import Link from 'next/link'

type Lang = 'bg' | 'de'

const copy = {
  de: {
    nav: ['Dienstleistungen', 'Vorteile', 'Kontakt'], login: 'Anmelden', toggle: 'BG',
    heroEyebrow: 'ENERGIE NEU GEDACHT', heroTitle: <>Mehr aus Ihrer<br /><em>Energie.</em></>, heroText: 'Wir helfen Ihnen, Energiekosten zu verstehen, zu optimieren und dauerhaft zu senken. Persönlich. Unabhängig. Transparent.', discover: 'Potenzial entdecken', more: 'Mehr erfahren', energy: 'ENERGIE', simple: 'EINFACH', effective: 'WIRKSAM', trust: 'Vertrauen, das sich auszahlt', independent: 'unabhängig', available: 'für Sie da', potential: 'Potenzial', approach: 'UNSER ANSATZ', approachTitle: <>Energie verstehen.<br /><em>Vorteile nutzen.</em></>, approachText: 'Komplexe Energiethemen werden bei uns zu klaren Entscheidungen. Damit Sie sich auf das konzentrieren können, was wirklich zählt.', clearTitle: <>Klarheit statt<br />Kleingedrucktes.</>, clearText: 'Wir übersetzen Tarife und Zahlen in verständliche Empfehlungen – ohne Fachchinesisch.', independentTitle: <>Unabhängig<br />beraten.</>, independentText: 'Unsere Empfehlung richtet sich nach Ihren Zielen – nicht nach Provisionen.', footerLead: <>Ihre Energie. Ihre Entscheidung.<br />Wir machen sie einfacher.</>, navigation: 'Navigation', legal: 'Rechtliches', contact: 'Kontakt', weekdays: 'Mo–Fr, 9:00–18:00 Uhr', services: 'Dienstleistungen', privacy: 'Datenschutz', terms: 'AGB', imprint: 'Impressum'
  },
  bg: {
    nav: ['Услуги', 'Предимства', 'Контакт'], login: 'Вход', toggle: 'DE',
    heroEyebrow: 'ЕНЕРГИЯ, ПРЕОСМИСЛЕНА', heroTitle: <>Повече от Вашата<br /><em>енергия.</em></>, heroText: 'Помагаме Ви да разберете, оптимизирате и трайно намалите енергийните си разходи. Лично. Независимо. Прозрачно.', discover: 'Открийте потенциала', more: 'Научете повече', energy: 'ЕНЕРГИЯ', simple: 'ЛЕСНО', effective: 'ЕФЕКТИВНО', trust: 'Доверие, което се изплаща', independent: 'независими', available: 'винаги до Вас', potential: 'потенциал', approach: 'НАШИЯТ ПОДХОД', approachTitle: <>Разберете енергията.<br /><em>Използвайте предимствата.</em></>, approachText: 'Сложните енергийни теми превръщаме в ясни решения, за да се фокусирате върху това, което наистина има значение.', clearTitle: <>Яснота вместо<br />дребен шрифт.</>, clearText: 'Превеждаме тарифите и числата в разбираеми препоръки – без сложен жаргон.', independentTitle: <>Независима<br />консултация.</>, independentText: 'Нашите препоръки са съобразени с Вашите цели – не с комисиони.', footerLead: <>Вашата енергия. Вашето решение.<br />Ние го правим по-лесно.</>, navigation: 'Навигация', legal: 'Правна информация', contact: 'Контакт', weekdays: 'Пн–Пт, 9:00–18:00 ч.', services: 'Услуги', privacy: 'Поверителност', terms: 'Общи условия', imprint: 'Импресум'
  }
}

function Header({ lang, setLang }: { lang: Lang; setLang: (lang: Lang) => void }) {
  const [open, setOpen] = useState(false); const t = copy[lang]
  return <header className="site-header"><div className="container nav-inner"><Link href="/" className="brand" onClick={() => setOpen(false)}><span className="brand-mark">t</span><span>Tarifberater<span className="brand-accent">24</span></span></Link><nav className={`desktop-nav ${open ? 'is-open' : ''}`} aria-label="Navigation"><Link href="/dienstleistungen">{t.nav[0]}</Link><Link href="/#vorteile">{t.nav[1]}</Link><Link href="/#kontakt">{t.nav[2]}</Link><Link href="/login" className="nav-login">{t.login}</Link><button className="language-switch" onClick={() => setLang(lang === 'de' ? 'bg' : 'de')} aria-label={`Switch language to ${t.toggle}`}>{lang.toUpperCase()} <span>/</span> {t.toggle}</button></nav><button className="menu-button" aria-label="Open menu" aria-expanded={open} onClick={() => setOpen(!open)}><span /><span /><span /></button></div></header>
}

function Footer({ lang, setLang }: { lang: Lang; setLang: (lang: Lang) => void }) { const t = copy[lang]; return <footer className="footer"><div className="container footer-grid"><div><Link href="/" className="brand footer-brand"><span className="brand-mark">t</span><span>Tarifberater<span className="brand-accent">24</span></span></Link><p>{t.footerLead}</p></div><div><h3>{t.navigation}</h3><Link href="/dienstleistungen">{t.services}</Link><Link href="/login">{t.login}</Link></div><div><h3>{t.legal}</h3><Link href="/impressum">{t.imprint}</Link><Link href="/datenschutz">{t.privacy}</Link><Link href="/agb">{t.terms}</Link></div><div><h3>{t.contact}</h3><a href="mailto:info@tarifberater24.de">info@tarifberater24.de</a><span>{t.weekdays}</span><button className="language-switch footer-switch" onClick={() => setLang(lang === 'de' ? 'bg' : 'de')}>{lang.toUpperCase()} <span>/</span> {t.toggle}</button></div></div><div className="container footer-bottom"><span>© 2024 Tarifberater24</span><span>Made for better decisions.</span></div></footer> }

function Home({ lang, setLang }: { lang: Lang; setLang: (lang: Lang) => void }) { const t = copy[lang]; return <><Header lang={lang} setLang={setLang} /><main><section className="hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow">{t.heroEyebrow}</p><h1>{t.heroTitle}</h1><p className="hero-text">{t.heroText}</p><div className="hero-actions"><Link href="/dienstleistungen" className="button button-dark">{t.discover} <span>↗</span></Link><Link href="#vorteile" className="text-link">{t.more} <span>↓</span></Link></div></div><div className="hero-art" aria-label="Energy efficiency"><div className="art-ring ring-one" /><div className="art-ring ring-two" /><div className="art-core"><span>24</span><small>{t.energy}</small></div><div className="art-label label-top">{t.simple}</div><div className="art-label label-bottom">{t.effective}</div></div></div></section><section className="trust"><div className="container trust-inner"><span>{t.trust}</span><div><b>100%</b><small>{t.independent}</small></div><div><b>24/7</b><small>{t.available}</small></div><div><b>∞</b><small>{t.potential}</small></div></div></section><section className="section" id="vorteile"><div className="container"><div className="section-intro"><p className="eyebrow">{t.approach}</p><h2>{t.approachTitle}</h2><p>{t.approachText}</p></div><div className="feature-grid"><div className="feature-card feature-main"><span className="card-number">01</span><div><h3>{t.clearTitle}</h3><p>{t.clearText}</p></div><span className="card-arrow">↗</span></div><div className="feature-card feature-light"><span className="card-number">02</span><div><h3>{t.independentTitle}</h3><p>{t.independentText}</p></div></div></div></div></section></main><Footer lang={lang} setLang={setLang} /></> }

export function SitePage({ path = '/' }: { path?: string }) { const [lang, setLang] = useState<Lang>('de'); return <Home lang={lang} setLang={setLang} /> }
export default function Page() { return <SitePage /> }

